name: amazon-sales-dashboard

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - plotly
  - altair
  - shiny
  - shinywidgets
  - anywidget
  - geopandas
  - folium
  - scikit-learn
  - scipy
  - jupyterlab
  - ipykernel
  - requests
  - duckdb
  - pyarrow
  - pytest
  - pytest-playwright
  - playwright